#!/bin/sh

options="Logout
Reboot
Shutdown
Suspend"

case  "$(printf '%s\n' "$options" | dmenu -l 5 -c -bw 5 -p "Power menu:")" in
    Shutdown) loginctl poweroff ;;
    Logout) loginctl kill-session self ;;
    Reboot) loginctl reboot ;;
    Suspend) loginctl suspend ;;
    *) echo "Programm terminated!" && exit 1 ;;
esac
