#!/bin/sh

options="Logout
Reboot
Shutdown
Suspend"

pidof systemd && power_manager="systemctl" || power_manager="loginctl" 

case  "$(printf '%s\n' "$options" | dmenu -l 5 -c -bw 5 -p "Power menu:")" in
    Shutdown) shutdown now ;;
    Logout) loginctl kill-session self ;;
    Reboot) loginctl reboot ;;
    Suspend) $power_manager suspend ;;
    *) echo "Programm terminated!" && exit 1 ;;
esac
