#!/bin/sh

DIMENSIONS=$(xdpyinfo | grep 'dimensions:' | awk '{print $2}')
RECORD_CMD="ffmpeg -video_size $DIMENSIONS -framerate 25 -f x11grab -i :0.0+0,0 -pix_fmt yuv420p -c:v libx265 -crf 18 -preset ultrafast"
VIDEO_DIR="$HOME/Media/Video/Screencasts"
VIDEO_PATH=$VIDEO_DIR/"$(date '+%Y_%m_%d_%H_%M')_record.mp4"

start_record ()
{
    $RECORD_CMD $VIDEO_PATH &
    dunstify -a ffmpeg -u low "" "Record started."
}

stop_record ()
{
    pkill ffmpeg 
    dunstify -a ffmpeg -u low "" "Record stopped."
}

case "$1" in
    "start") start_record ;;
    "stop") stop_record ;;
    *) echo "Unknow command" ;;
esac

