#!/bin/sh


wall_dir="$HOME/.local/share/wallpapers"
bg_loc="${XDG_DATA_HOME:-$HOME/.local/share/}/$wall_name"

if [ -z "$1" ]; then
  wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n1)"
else
  wall="$1"
fi

ln -sf "$(readlink -f "$wall")"  "$bg_loc"
wal -c
wal -s -i "$wall"

xwallpaper --zoom "$bg_loc"
xdotool key super+F5
cp ~/.cache/wal/colors-kitty.conf ~/.config/kitty
dunst_xr
pkill dunst  
dunst &
disown
