#!/bin/bash

# Prints the current song in mpd.
case $BUTTON in
    1) mpc toggle ;;
    2) toggle_playlist ;;
    3) dunstify -a "Music module." " " "Show current song 
- Scroll to change.
- Click to toggle.
- Middle click to change playlist." ;;
    4) mpc next ;;
    5) mpc prev ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo "$(mpc current)"
