#!/bin/sh

# Prints the current volume or 🔇 if muted.
case $BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) dunstify -a  "📢 Volume module." "Shows volume 🔊
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pulsemixer --get-mute)  = "1" ] && echo 🔇 && exit

vol="$(pulsemixer --get-volume | cut -d ' ' -f 2)"

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -gt "30" ]; then
	icon="🔉"
elif [ "$vol" -gt "0" ]; then
	icon="🔈"
else
        echo 🔇 && exit
fi

echo "$icon $vol%"
