#!/bin/sh

# Prints the current volume or 🔇 if muted.
case $BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pactl set-sink-volume @DEFAULT_SINK@ +5% ;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -5% ;;
	3) dunstify -a  "📢 Volume module." "Shows volume 🔊
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute)  = "true" ] && echo 🔇 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
elif [ "$vol" -gt "0" ]; then
	icon=""
else
        echo 🔇 && exit
fi

echo "$icon $vol%"
