WM="qtile"

# Set keyboard layout
setxkbmap -layout us,ru -option grp:alt_shift_toggle

# load Xresources
xrdb -load "$HOME/.config/x11/$xresources_name"

# Start polkit manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Dwm bar
[ $WM = "dwm" ] && dwmblocks &

# Wallpapers
xwallpaper --zoom "$HOME/.local/share/$wall_name" &

# Compositor
picom & 

# Start notifications manager
dunst &
notify-send -a "System." "" "Hi !" -i "~/.config/dunst/icons/welcome.svg"

# Start redshift
redshift &

# Load mpd playlist
start_mpd &

# Key bindings.
sxhkd &

# Hide mouse cursor.
unclutter -idle 3 &

# Screenshots.
flameshot &

# Sync files. 
syncthing --no-browser &

# Custom lock.
xss-lock slock &

while true; do
   [ $WM = "qtile" ] && qtile start
   [ $WM = "dwm" ] && dwm 
done
