# qtile dwm
export WM="dwm"

# start rootless docker 
dockerd-rootless.sh  &

# Set keyboard layout
setxkbmap -layout us,ru -option grp:alt_shift_toggle

# load Xresources
echo "Xft.dpi: $DPI" | xrdb -merge
wal -R
dunsx_xr 

# Start notifications manager
dunst &
dunstify -a "System" "" 'Hi!' -i "$HOME/.local/share/themes/GRUB/nord/icons/artix.png" &

# dwm bar 
[ "$WM" = "dwm" ] && dwm_bar &

# Compositor
picom --experimental-backends &

# Wallpapers
xwallpaper --zoom "$HOME/.local/share/$wall_name" &

# Start redshift
redshift &

# Load mpd playlist
start_mpd &

# Key bindings.
sxhkd &

# Hide mouse cursor.
unclutter -idle 3 &

# Screenshots.
flameshot &

# Sync files. 
syncthing --no-browser &

# Custom lock.
xss-lock slock &

while true; do
   [ $WM = "qtile" ] && qtile start
   [ $WM = "dwm" ] && dwm 
   [ $WM = "hyprland" ] && hyprland 
done
