WM="dwm"

# Start polkit manager
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set keyboard layout
setxkbmap -layout us,ru -option grp:alt_shift_toggle

# load Xresources
xrdb -load ~/.config/x11/Xresources

# Start volume stuff.
pipewire &
pipewire-pulse &
pipewire-media-session &

# Wallpapers
xwallpaper --zoom "$HOME/.local/share/bg"

# Start notifications manager
dunst &
notify-send -a "System." "Hi !" -i "~/.config/dunst/icons/welcome.svg"

# Warm display.
redshift &

# Hotkeys daemon
sxhkd &

# Sustom screen lock.
xss-lock slock &

# Screenshots.
flameshot &

# Compositing
picom --experimental-backends &

# Load mpd playlist
mpd
mpc load "Music"
mpc play
mpc pause

# Sync files.
syncthing --no-browser &

# Local search.
/usr/bin/uwsgi --ini /etc/uwsgi/searxng.ini &

# Dwm bar
[ $WM = "dwm" ] && dwmblocks &

while true; do
   [ $WM = "qtile" ] && qtile start
   [ $WM = "dwm" ] && dwm 
   # [ $WM = "dwm" ] && dwm >> ~/.cache/dwm.log 2>&1
done
